// <auto-generated />
using System;
using LIBRARY_SYSTEM_PRACTICE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIBRARY_SYSTEM_PRACTICE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005113241_Init Migration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BookPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "John Doe",
                            BookPrice = 29.99m,
                            CategoryId = 1,
                            ISBN = "978-1234567890",
                            IsAvailable = true,
                            Title = "C# Programming"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "John Smith",
                            BookPrice = 450m,
                            CategoryId = 2,
                            ISBN = "ISBN001",
                            IsAvailable = false,
                            Title = "C++ Basics"
                        });
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Borrowing", b =>
                {
                    b.Property<int>("BorrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowingId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowingId");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            BorrowingId = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 9, 28, 14, 32, 40, 840, DateTimeKind.Local).AddTicks(588),
                            MemberId = 1
                        },
                        new
                        {
                            BorrowingId = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 9, 30, 14, 32, 40, 840, DateTimeKind.Local).AddTicks(648),
                            MemberId = 2,
                            ReturnDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Programming and software development books",
                            CategoryName = "Programming"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Database and data management books",
                            CategoryName = "Database"
                        });
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("MemberEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.HasIndex("MemberEmail")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            MemberEmail = "ahmedhass@gmail.com",
                            MemberFullName = "Ahmed Hassan",
                            MemberPhone = "01012345678"
                        },
                        new
                        {
                            MemberId = 2,
                            MemberEmail = "sara@example.com",
                            MemberFullName = "Sara Mohamed",
                            MemberPhone = "01198765432"
                        });
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Book", b =>
                {
                    b.HasOne("LIBRARY_SYSTEM_PRACTICE.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Borrowing", b =>
                {
                    b.HasOne("LIBRARY_SYSTEM_PRACTICE.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIBRARY_SYSTEM_PRACTICE.Models.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Book", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LIBRARY_SYSTEM_PRACTICE.Models.Member", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
